### PR TITLE
Issues #13 and #16 - failures on changed collection names and random order of node_modules vs overriden extensions

### PR DESCRIPTION
**Pull request by weidox**

### CODE REVIEW

**Comment by aperron** [comment]
Hello, i tried an simpler solution. Could you see branch [feature/model_name_with_filename](https://github.com/erikvullings/strapi-to-typescript/tree/feature/model_name_with_filename), if that meets your need.

In summary, i added param `fieldname` on custom function `interfaceName`. So you can do something like:

```typescript
    interfaceName(name, fieldname){
        const modelNameStep1 = fieldname.slice(fieldname.lastIndexOf('\\') + 1) //windows
        const modelNameStep2 = modelNameStep1.slice(modelNameStep1.lastIndexOf('/') + 1) //linux
        const modelName = modelNameStep2.slice(0, modelNameStep2.indexOf('.')).toLowerCase() //cut all extensions and to lowercase
        return modelName;
    },
```

**Comment by weidox** [comment]
@aperron My PR fixes deeper issue about failing interface references linking, plus random failures to generate proper interfaces for models overridden from extensions, which your PR does not address. On interface name, it's possible to remove all wrong symbols from collection name (my own function below based on our naming convention) and have a nice interface name. But putting modelName into your PR instead of fileName (after merging my PR) would be helpful. 

```
      interfaceName: (name) => {
      const dash = name.indexOf('-');
      const s = name.slice(dash + 1).replace(/ |-/g, '');
      return s[0].toUpperCase() + s.slice(1); 
    }, 
```

**Comment by aperron** [comment]
ok, it should be good with my latest commits

**Comment by aperron** [comment]
let me know if it's ok for you

**Comment by weidox** [comment]
@aperron I reviewed your code, you made it in nice way, did not know that path can extract filename piece so easily, and did not know existing code enough to understand that it's possible to do all stuff just in exporter. There's still that one remaining issue for which I wrote a //TODO - change how component model name is extracted to include one directory above. If you need help on that one, I'd try to find time again for some messy PR for general idea.

**Comment by weidox** [comment]
Though doing everything in exporter is slightly incorrect - as a really dumb corner case someone could make two different collections with same name, while model names would be always unique (with presumption that missing fix for component model name would be implemented). But we probably may not care about people doing dumb things:)

**Comment by aperron** [comment]
I know there are limitations with the current system but if there is no specific request, for the moment it will be fine. I close your PR.
I'm waiting for a little fix on another PR and I release ASAP.

**Pull request closed without merging**
